export const SET_RESOURCES = 'SET_RESOURCES'
export const SET_CATEGORIES = 'SET_CATEGORIES'
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'

export const GET_RESOURCE = 'GET_RESOURCE'
export const CHG_CURRENT_RESOURCE = 'CHG_CURRENT_RESOURCE'
export const CLEAR_CURRENT_RESOURCE = 'CLEAR_CURRENT_RESOURCE'

export const CURRENT_CAT = 'CURRENT_CAT'
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const RESET_ADD_CAT_FORM = 'RESET_ADD_CAT_FORM'
export const CHANGE_CURRENT_CATEGORY = 'CHANGE_CURRENT_CATEGORY'
